// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


var header = {
  color: "#444444",
  fontSize: "68px"
};

var title = {
  color: "#444444",
  fontSize: "28px"
};

exports.header = header;
exports.title = title;
/* No side effect */
