// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Str$ReactTemplate = require("./Str.bs.js");

var FetcherComponent = /* module */[];

var str = Str$ReactTemplate.txt;

exports.str = str;
exports.FetcherComponent = FetcherComponent;
/* No side effect */
