// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var HeaderStyles$ReactTemplate = require("../header/HeaderStyles.bs.js");

var component = ReasonReact.statelessComponent("Header");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("header", {
                  style: HeaderStyles$ReactTemplate.header
                }, React.createElement("h1", {
                      style: HeaderStyles$ReactTemplate.title
                    }, "Book My Hooptie!"));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
