// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var FooterStyles$ReactTemplate = require("./FooterStyles.bs.js");

var component = ReasonReact.statelessComponent("Header");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("footer", {
                  style: FooterStyles$ReactTemplate.footer
                }, React.createElement("h1", {
                      style: FooterStyles$ReactTemplate.text
                    }, "Copyright 2018, Book my Hooptie"));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
