// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


var footer = {
  color: "#444444",
  fontSize: "68px"
};

var text = {
  color: "#444444",
  fontSize: "28px"
};

exports.footer = footer;
exports.text = text;
/* No side effect */
