// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Str$ReactTemplate = require("../../utils/Str.bs.js");

var component = ReasonReact.statelessComponent("BookingForm");

function translate(string) {
  return string;
}

function make(pickup, dropoff, time, pickupDate, updatePickup, updateDate, updateDropoff, updateTime, bookingAction) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("form", {
                  className: "form"
                }, React.createElement("fieldset", {
                      className: "fieldset"
                    }, React.createElement("legend", {
                          className: "legend"
                        }, Str$ReactTemplate.txt("booking.legend")), React.createElement("input", {
                          label: "pickup.label",
                          name: "pickup",
                          placeholder: "pickup.placeholder",
                          type: "text",
                          value: pickup,
                          onChange: updatePickup
                        }), React.createElement("input", {
                          label: "dropoff.label",
                          name: "dropoff",
                          placeholder: "dropoff.placeholder",
                          type: "text",
                          value: dropoff,
                          onChange: updateDropoff
                        })), React.createElement("fieldset", {
                      className: "fieldset"
                    }, React.createElement("label", {
                          className: "label",
                          htmlFor: "pickup-date"
                        }, Str$ReactTemplate.txt("booking.pickupDate")), React.createElement("input", {
                          className: "input",
                          id: "pickup-date",
                          type: "date",
                          value: pickupDate,
                          onChange: updateDate
                        }), React.createElement("label", {
                          className: "label",
                          htmlFor: "pickup-time"
                        }, Str$ReactTemplate.txt("booking.pickupTime")), React.createElement("input", {
                          className: "input",
                          type: "time",
                          value: time,
                          onChange: updateTime
                        })), React.createElement("div", {
                      className: "buttonContainer"
                    }, React.createElement("button", {
                          className: "button",
                          onClick: bookingAction
                        }, Str$ReactTemplate.txt("booking.bookNow"))));
    });
  return newrecord;
}

var str = Str$ReactTemplate.txt;

exports.component = component;
exports.str = str;
exports.translate = translate;
exports.make = make;
/* component Not a pure module */
