// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Footer$ReactTemplate = require("./components/footer/Footer.bs.js");
var Header$ReactTemplate = require("./components/header/Header.bs.js");
var BookingForm$ReactTemplate = require("./components/booking-form/BookingForm.bs.js");

var component = ReasonReact.statelessComponent("Page");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Header$ReactTemplate.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, BookingForm$ReactTemplate.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, Footer$ReactTemplate.make(/* array */[])));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
